// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// aldd0
double aldd0(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, const arma::vec& yvec, const arma::vec& tau, const arma::vec& C, const arma::uvec& dupid, int dcate);
RcppExport SEXP _evgam_aldd0(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP yvecSEXP, SEXP tauSEXP, SEXP CSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(aldd0(pars, X1, X2, yvec, tau, C, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// aldd12
arma::mat aldd12(const Rcpp::List& pars, arma::mat X1, arma::mat X2, const arma::vec& yvec, const arma::vec& tau, const arma::vec& C, const arma::uvec& dupid, int dcate);
RcppExport SEXP _evgam_aldd12(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP yvecSEXP, SEXP tauSEXP, SEXP CSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(aldd12(pars, X1, X2, yvec, tau, C, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// aldd34
arma::mat aldd34(const Rcpp::List& pars, arma::mat X1, arma::mat X2, const arma::vec& yvec, const arma::vec& tau, const arma::vec& C, const arma::uvec& dupid, int dcate);
RcppExport SEXP _evgam_aldd34(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP yvecSEXP, SEXP tauSEXP, SEXP CSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(aldd34(pars, X1, X2, yvec, tau, C, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// egpd1d0
double egpd1d0(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, const arma::mat& X3, arma::vec yvec, const arma::uvec& dupid, int dcate);
RcppExport SEXP _evgam_egpd1d0(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(egpd1d0(pars, X1, X2, X3, yvec, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// egpd1d12
arma::mat egpd1d12(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::vec yvec, const arma::uvec dupid, int dcate);
RcppExport SEXP _evgam_egpd1d12(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(egpd1d12(pars, X1, X2, X3, yvec, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// egpd1d34
arma::mat egpd1d34(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::vec yvec, const arma::uvec dupid, int dcate);
RcppExport SEXP _evgam_egpd1d34(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(egpd1d34(pars, X1, X2, X3, yvec, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// egpd2d0
double egpd2d0(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, const arma::mat& X3, const arma::mat& X4, const arma::mat& X5, arma::vec yvec, const arma::uvec& dupid, int dcate);
RcppExport SEXP _evgam_egpd2d0(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP X5SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X5(X5SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(egpd2d0(pars, X1, X2, X3, X4, X5, yvec, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// egpd2d12
arma::mat egpd2d12(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, const arma::mat& X3, const arma::mat& X4, const arma::mat& X5, arma::vec yvec, const arma::uvec& dupid, int dcate);
RcppExport SEXP _evgam_egpd2d12(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP X5SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X5(X5SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(egpd2d12(pars, X1, X2, X3, X4, X5, yvec, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// egpd2d34
arma::mat egpd2d34(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, const arma::mat& X3, const arma::mat& X4, const arma::mat& X5, arma::vec yvec, const arma::uvec& dupid, int dcate);
RcppExport SEXP _evgam_egpd2d34(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP X5SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X5(X5SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(egpd2d34(pars, X1, X2, X3, X4, X5, yvec, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// egpd3d0
double egpd3d0(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, const arma::mat& X3, arma::vec yvec, const arma::uvec& dupid, int dcate);
RcppExport SEXP _evgam_egpd3d0(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(egpd3d0(pars, X1, X2, X3, yvec, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// egpd3d12
arma::mat egpd3d12(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::vec yvec, const arma::uvec dupid, int dcate);
RcppExport SEXP _evgam_egpd3d12(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(egpd3d12(pars, X1, X2, X3, yvec, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// egpd3d34
arma::mat egpd3d34(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::vec yvec, const arma::uvec dupid, int dcate);
RcppExport SEXP _evgam_egpd3d34(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(egpd3d34(pars, X1, X2, X3, yvec, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// egpd4d0
double egpd4d0(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, const arma::mat& X3, const arma::mat& X4, arma::vec yvec, const arma::uvec& dupid, int dcate);
RcppExport SEXP _evgam_egpd4d0(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(egpd4d0(pars, X1, X2, X3, X4, yvec, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// egpd4d12
arma::mat egpd4d12(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::mat X4, arma::vec yvec, const arma::uvec dupid, int dcate);
RcppExport SEXP _evgam_egpd4d12(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(egpd4d12(pars, X1, X2, X3, X4, yvec, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// egpd4d34
arma::mat egpd4d34(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::mat X4, arma::vec yvec, const arma::uvec dupid, int dcate);
RcppExport SEXP _evgam_egpd4d34(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(egpd4d34(pars, X1, X2, X3, X4, yvec, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// exid0
double exid0(arma::vec yvec, arma::uvec zvec, arma::vec pars, arma::vec nmax, arma::mat X, arma::uvec dupid, int dcate, int link);
RcppExport SEXP _evgam_exid0(SEXP yvecSEXP, SEXP zvecSEXP, SEXP parsSEXP, SEXP nmaxSEXP, SEXP XSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP linkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type zvec(zvecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type nmax(nmaxSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< int >::type link(linkSEXP);
    rcpp_result_gen = Rcpp::wrap(exid0(yvec, zvec, pars, nmax, X, dupid, dcate, link));
    return rcpp_result_gen;
END_RCPP
}
// exid12
arma::mat exid12(arma::vec yvec, arma::uvec zvec, arma::vec pars, arma::vec nmax, arma::mat X, arma::uvec dupid, int dcate, int link);
RcppExport SEXP _evgam_exid12(SEXP yvecSEXP, SEXP zvecSEXP, SEXP parsSEXP, SEXP nmaxSEXP, SEXP XSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP linkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type zvec(zvecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type nmax(nmaxSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< int >::type link(linkSEXP);
    rcpp_result_gen = Rcpp::wrap(exid12(yvec, zvec, pars, nmax, X, dupid, dcate, link));
    return rcpp_result_gen;
END_RCPP
}
// exid34
arma::mat exid34(arma::vec yvec, arma::uvec zvec, arma::vec pars, arma::vec nmax, arma::mat X, arma::uvec dupid, int dcate, int link);
RcppExport SEXP _evgam_exid34(SEXP yvecSEXP, SEXP zvecSEXP, SEXP parsSEXP, SEXP nmaxSEXP, SEXP XSEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP linkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type zvec(zvecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type nmax(nmaxSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< int >::type link(linkSEXP);
    rcpp_result_gen = Rcpp::wrap(exid34(yvec, zvec, pars, nmax, X, dupid, dcate, link));
    return rcpp_result_gen;
END_RCPP
}
// runmax
arma::vec runmax(arma::vec y, int n);
RcppExport SEXP _evgam_runmax(SEXP ySEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(runmax(y, n));
    return rcpp_result_gen;
END_RCPP
}
// expd0
double expd0(const Rcpp::List& pars, const arma::mat& X1, arma::vec yvec, const arma::uvec dupid, int dcate);
RcppExport SEXP _evgam_expd0(SEXP parsSEXP, SEXP X1SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(expd0(pars, X1, yvec, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// expd12
arma::mat expd12(const Rcpp::List& pars, arma::mat X1, arma::vec yvec, const arma::uvec dupid, int dcate);
RcppExport SEXP _evgam_expd12(SEXP parsSEXP, SEXP X1SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(expd12(pars, X1, yvec, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// expd34
arma::mat expd34(const Rcpp::List& pars, arma::mat X1, arma::vec yvec, const arma::uvec dupid, int dcate);
RcppExport SEXP _evgam_expd34(SEXP parsSEXP, SEXP X1SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(expd34(pars, X1, yvec, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// armapinv
arma::mat armapinv(arma::mat x, double tol);
RcppExport SEXP _evgam_armapinv(SEXP xSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(armapinv(x, tol));
    return rcpp_result_gen;
END_RCPP
}
// armaginv
arma::mat armaginv(arma::mat x, double tol);
RcppExport SEXP _evgam_armaginv(SEXP xSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(armaginv(x, tol));
    return rcpp_result_gen;
END_RCPP
}
// gaussd0
double gaussd0(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, arma::vec yvec, const arma::uvec& dupid, int dcate);
RcppExport SEXP _evgam_gaussd0(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussd0(pars, X1, X2, yvec, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// gaussd12
arma::mat gaussd12(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, arma::vec yvec, const arma::uvec& dupid, int dcate);
RcppExport SEXP _evgam_gaussd12(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussd12(pars, X1, X2, yvec, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// gaussd34
arma::mat gaussd34(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, arma::vec yvec, const arma::uvec& dupid, int dcate);
RcppExport SEXP _evgam_gaussd34(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussd34(pars, X1, X2, yvec, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// gevd0
double gevd0(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, const arma::mat& X3, arma::vec yvec, const arma::uvec& dupid, int dcate);
RcppExport SEXP _evgam_gevd0(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(gevd0(pars, X1, X2, X3, yvec, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// gevd12
arma::mat gevd12(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::vec yvec, const arma::uvec dupid, int dcate);
RcppExport SEXP _evgam_gevd12(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(gevd12(pars, X1, X2, X3, yvec, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// gevd34
arma::mat gevd34(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::vec yvec, const arma::uvec dupid, int dcate);
RcppExport SEXP _evgam_gevd34(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(gevd34(pars, X1, X2, X3, yvec, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// mean_arr
arma::mat mean_arr(arma::mat x, double n);
RcppExport SEXP _evgam_mean_arr(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(mean_arr(x, n));
    return rcpp_result_gen;
END_RCPP
}
// ragged_mean_vec
arma::vec ragged_mean_vec(arma::vec x, arma::uvec n);
RcppExport SEXP _evgam_ragged_mean_vec(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(ragged_mean_vec(x, n));
    return rcpp_result_gen;
END_RCPP
}
// ragged_mean_mat
arma::mat ragged_mean_mat(arma::mat x, arma::uvec n);
RcppExport SEXP _evgam_ragged_mean_mat(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(ragged_mean_mat(x, n));
    return rcpp_result_gen;
END_RCPP
}
// ldgev
double ldgev(arma::vec yvec, arma::vec muvec, arma::vec lpsivec, arma::vec xivec);
RcppExport SEXP _evgam_ldgev(SEXP yvecSEXP, SEXP muvecSEXP, SEXP lpsivecSEXP, SEXP xivecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type muvec(muvecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lpsivec(lpsivecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xivec(xivecSEXP);
    rcpp_result_gen = Rcpp::wrap(ldgev(yvec, muvec, lpsivec, xivec));
    return rcpp_result_gen;
END_RCPP
}
// ldgev12
arma::mat ldgev12(arma::vec yvec, arma::vec muvec, arma::vec lpsivec, arma::vec xivec);
RcppExport SEXP _evgam_ldgev12(SEXP yvecSEXP, SEXP muvecSEXP, SEXP lpsivecSEXP, SEXP xivecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type muvec(muvecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lpsivec(lpsivecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xivec(xivecSEXP);
    rcpp_result_gen = Rcpp::wrap(ldgev12(yvec, muvec, lpsivec, xivec));
    return rcpp_result_gen;
END_RCPP
}
// ldgevagg
double ldgevagg(arma::vec yvec, arma::vec muvec, arma::vec lpsivec, arma::vec xivec, arma::vec thetavec);
RcppExport SEXP _evgam_ldgevagg(SEXP yvecSEXP, SEXP muvecSEXP, SEXP lpsivecSEXP, SEXP xivecSEXP, SEXP thetavecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type muvec(muvecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lpsivec(lpsivecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xivec(xivecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type thetavec(thetavecSEXP);
    rcpp_result_gen = Rcpp::wrap(ldgevagg(yvec, muvec, lpsivec, xivec, thetavec));
    return rcpp_result_gen;
END_RCPP
}
// ldgevagg12
arma::mat ldgevagg12(arma::vec yvec, arma::vec muvec, arma::vec lpsivec, arma::vec xivec, arma::vec thetavec);
RcppExport SEXP _evgam_ldgevagg12(SEXP yvecSEXP, SEXP muvecSEXP, SEXP lpsivecSEXP, SEXP xivecSEXP, SEXP thetavecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type muvec(muvecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lpsivec(lpsivecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xivec(xivecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type thetavec(thetavecSEXP);
    rcpp_result_gen = Rcpp::wrap(ldgevagg12(yvec, muvec, lpsivec, xivec, thetavec));
    return rcpp_result_gen;
END_RCPP
}
// gevcd0
double gevcd0(Rcpp::List pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::mat ymat, arma::uvec dupid, int dcate);
RcppExport SEXP _evgam_gevcd0(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP ymatSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ymat(ymatSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(gevcd0(pars, X1, X2, X3, ymat, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// gevcd12
arma::mat gevcd12(Rcpp::List pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::mat ymat, arma::uvec dupid, int dcate);
RcppExport SEXP _evgam_gevcd12(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP ymatSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ymat(ymatSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(gevcd12(pars, X1, X2, X3, ymat, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// gevcd34
arma::mat gevcd34(Rcpp::List pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::mat ymat, arma::uvec dupid, int dcate);
RcppExport SEXP _evgam_gevcd34(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP ymatSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ymat(ymatSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(gevcd34(pars, X1, X2, X3, ymat, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// gpdd0
double gpdd0(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, arma::vec yvec, const arma::uvec& dupid, int dcate);
RcppExport SEXP _evgam_gpdd0(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(gpdd0(pars, X1, X2, yvec, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// gpdd12
arma::mat gpdd12(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::vec yvec, const arma::uvec dupid, int dcate);
RcppExport SEXP _evgam_gpdd12(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(gpdd12(pars, X1, X2, yvec, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// gpdd34
arma::mat gpdd34(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::vec yvec, const arma::uvec dupid, int dcate);
RcppExport SEXP _evgam_gpdd34(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(gpdd34(pars, X1, X2, yvec, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// gpdcd0
double gpdcd0(Rcpp::List pars, arma::mat X1, arma::mat X2, arma::mat ymat, arma::uvec dupid, int dcate);
RcppExport SEXP _evgam_gpdcd0(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP ymatSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ymat(ymatSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(gpdcd0(pars, X1, X2, ymat, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// gpdcd12
arma::mat gpdcd12(Rcpp::List pars, arma::mat X1, arma::mat X2, arma::mat ymat, arma::uvec dupid, int dcate);
RcppExport SEXP _evgam_gpdcd12(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP ymatSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ymat(ymatSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(gpdcd12(pars, X1, X2, ymat, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// gpdcd34
arma::mat gpdcd34(Rcpp::List pars, arma::mat X1, arma::mat X2, arma::mat ymat, arma::uvec dupid, int dcate);
RcppExport SEXP _evgam_gpdcd34(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP ymatSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ymat(ymatSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(gpdcd34(pars, X1, X2, ymat, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// gH1
Rcpp::List gH1(arma::mat gh, arma::mat X1, const arma::uvec dupid, int dcate, int sand, int deriv);
RcppExport SEXP _evgam_gH1(SEXP ghSEXP, SEXP X1SEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP sandSEXP, SEXP derivSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type gh(ghSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< int >::type sand(sandSEXP);
    Rcpp::traits::input_parameter< int >::type deriv(derivSEXP);
    rcpp_result_gen = Rcpp::wrap(gH1(gh, X1, dupid, dcate, sand, deriv));
    return rcpp_result_gen;
END_RCPP
}
// gH2
Rcpp::List gH2(arma::mat gh, arma::mat X1, arma::mat X2, const arma::uvec dupid, int dcate, int sand, int deriv);
RcppExport SEXP _evgam_gH2(SEXP ghSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP sandSEXP, SEXP derivSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type gh(ghSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< int >::type sand(sandSEXP);
    Rcpp::traits::input_parameter< int >::type deriv(derivSEXP);
    rcpp_result_gen = Rcpp::wrap(gH2(gh, X1, X2, dupid, dcate, sand, deriv));
    return rcpp_result_gen;
END_RCPP
}
// gH3
Rcpp::List gH3(arma::mat gh, arma::mat X1, arma::mat X2, arma::mat X3, const arma::uvec dupid, int dcate, int sand, int deriv);
RcppExport SEXP _evgam_gH3(SEXP ghSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP sandSEXP, SEXP derivSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type gh(ghSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< int >::type sand(sandSEXP);
    Rcpp::traits::input_parameter< int >::type deriv(derivSEXP);
    rcpp_result_gen = Rcpp::wrap(gH3(gh, X1, X2, X3, dupid, dcate, sand, deriv));
    return rcpp_result_gen;
END_RCPP
}
// gH4
Rcpp::List gH4(arma::mat gh, arma::mat X1, arma::mat X2, arma::mat X3, arma::mat X4, const arma::uvec dupid, int dcate, int sand, int deriv);
RcppExport SEXP _evgam_gH4(SEXP ghSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP sandSEXP, SEXP derivSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type gh(ghSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< int >::type sand(sandSEXP);
    Rcpp::traits::input_parameter< int >::type deriv(derivSEXP);
    rcpp_result_gen = Rcpp::wrap(gH4(gh, X1, X2, X3, X4, dupid, dcate, sand, deriv));
    return rcpp_result_gen;
END_RCPP
}
// gH5
Rcpp::List gH5(arma::mat gh, arma::mat X1, arma::mat X2, arma::mat X3, arma::mat X4, arma::mat X5, const arma::uvec dupid, int dcate, int sand, int deriv);
RcppExport SEXP _evgam_gH5(SEXP ghSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP X5SEXP, SEXP dupidSEXP, SEXP dcateSEXP, SEXP sandSEXP, SEXP derivSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type gh(ghSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X5(X5SEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    Rcpp::traits::input_parameter< int >::type sand(sandSEXP);
    Rcpp::traits::input_parameter< int >::type deriv(derivSEXP);
    rcpp_result_gen = Rcpp::wrap(gH5(gh, X1, X2, X3, X4, X5, dupid, dcate, sand, deriv));
    return rcpp_result_gen;
END_RCPP
}
// pp1d0
double pp1d0(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, const arma::mat& X3, arma::vec yvec, arma::vec wvec);
RcppExport SEXP _evgam_pp1d0(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP yvecSEXP, SEXP wvecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type wvec(wvecSEXP);
    rcpp_result_gen = Rcpp::wrap(pp1d0(pars, X1, X2, X3, yvec, wvec));
    return rcpp_result_gen;
END_RCPP
}
// pp1d12
arma::mat pp1d12(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::vec yvec, arma::vec wvec);
RcppExport SEXP _evgam_pp1d12(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP yvecSEXP, SEXP wvecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type wvec(wvecSEXP);
    rcpp_result_gen = Rcpp::wrap(pp1d12(pars, X1, X2, X3, yvec, wvec));
    return rcpp_result_gen;
END_RCPP
}
// pp1d34
arma::mat pp1d34(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::vec yvec, arma::vec wvec);
RcppExport SEXP _evgam_pp1d34(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP yvecSEXP, SEXP wvecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type wvec(wvecSEXP);
    rcpp_result_gen = Rcpp::wrap(pp1d34(pars, X1, X2, X3, yvec, wvec));
    return rcpp_result_gen;
END_RCPP
}
// pp2d0
double pp2d0(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, const arma::mat& X3, arma::vec yvec, arma::vec wvec);
RcppExport SEXP _evgam_pp2d0(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP yvecSEXP, SEXP wvecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type wvec(wvecSEXP);
    rcpp_result_gen = Rcpp::wrap(pp2d0(pars, X1, X2, X3, yvec, wvec));
    return rcpp_result_gen;
END_RCPP
}
// pp2d12
arma::mat pp2d12(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::vec yvec);
RcppExport SEXP _evgam_pp2d12(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP yvecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    rcpp_result_gen = Rcpp::wrap(pp2d12(pars, X1, X2, X3, yvec));
    return rcpp_result_gen;
END_RCPP
}
// pp2d34
arma::mat pp2d34(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::vec yvec);
RcppExport SEXP _evgam_pp2d34(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP yvecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    rcpp_result_gen = Rcpp::wrap(pp2d34(pars, X1, X2, X3, yvec));
    return rcpp_result_gen;
END_RCPP
}
// ppcd0
double ppcd0(const Rcpp::List& pars, const arma::mat& X1, const arma::mat& X2, const arma::mat& X3, arma::vec yvec, arma::vec wvec);
RcppExport SEXP _evgam_ppcd0(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP yvecSEXP, SEXP wvecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type wvec(wvecSEXP);
    rcpp_result_gen = Rcpp::wrap(ppcd0(pars, X1, X2, X3, yvec, wvec));
    return rcpp_result_gen;
END_RCPP
}
// ppcd12
arma::mat ppcd12(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::vec yvec);
RcppExport SEXP _evgam_ppcd12(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP yvecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    rcpp_result_gen = Rcpp::wrap(ppcd12(pars, X1, X2, X3, yvec));
    return rcpp_result_gen;
END_RCPP
}
// ppcd34
arma::mat ppcd34(const Rcpp::List& pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::vec yvec);
RcppExport SEXP _evgam_ppcd34(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP yvecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    rcpp_result_gen = Rcpp::wrap(ppcd34(pars, X1, X2, X3, yvec));
    return rcpp_result_gen;
END_RCPP
}
// ppexi1d0
double ppexi1d0(Rcpp::List pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::mat X4, arma::vec yvec, arma::vec wvec);
RcppExport SEXP _evgam_ppexi1d0(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP yvecSEXP, SEXP wvecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type wvec(wvecSEXP);
    rcpp_result_gen = Rcpp::wrap(ppexi1d0(pars, X1, X2, X3, X4, yvec, wvec));
    return rcpp_result_gen;
END_RCPP
}
// ppexi1d12
arma::mat ppexi1d12(Rcpp::List pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::mat X4, arma::vec yvec, arma::vec wvec);
RcppExport SEXP _evgam_ppexi1d12(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP yvecSEXP, SEXP wvecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type wvec(wvecSEXP);
    rcpp_result_gen = Rcpp::wrap(ppexi1d12(pars, X1, X2, X3, X4, yvec, wvec));
    return rcpp_result_gen;
END_RCPP
}
// ppexi1d34
arma::mat ppexi1d34(Rcpp::List pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::mat X4, arma::vec yvec, arma::vec wvec);
RcppExport SEXP _evgam_ppexi1d34(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP yvecSEXP, SEXP wvecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type wvec(wvecSEXP);
    rcpp_result_gen = Rcpp::wrap(ppexi1d34(pars, X1, X2, X3, X4, yvec, wvec));
    return rcpp_result_gen;
END_RCPP
}
// ppexi2d0
double ppexi2d0(Rcpp::List pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::mat X4, arma::vec yvec, arma::vec wvec);
RcppExport SEXP _evgam_ppexi2d0(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP yvecSEXP, SEXP wvecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type wvec(wvecSEXP);
    rcpp_result_gen = Rcpp::wrap(ppexi2d0(pars, X1, X2, X3, X4, yvec, wvec));
    return rcpp_result_gen;
END_RCPP
}
// ppexi2d12
arma::mat ppexi2d12(Rcpp::List pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::mat X4, arma::vec yvec, arma::vec wvec);
RcppExport SEXP _evgam_ppexi2d12(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP yvecSEXP, SEXP wvecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type wvec(wvecSEXP);
    rcpp_result_gen = Rcpp::wrap(ppexi2d12(pars, X1, X2, X3, X4, yvec, wvec));
    return rcpp_result_gen;
END_RCPP
}
// ppexi2d34
arma::mat ppexi2d34(Rcpp::List pars, arma::mat X1, arma::mat X2, arma::mat X3, arma::mat X4, arma::vec yvec, arma::vec wvec);
RcppExport SEXP _evgam_ppexi2d34(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP X3SEXP, SEXP X4SEXP, SEXP yvecSEXP, SEXP wvecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X3(X3SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X4(X4SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type wvec(wvecSEXP);
    rcpp_result_gen = Rcpp::wrap(ppexi2d34(pars, X1, X2, X3, X4, yvec, wvec));
    return rcpp_result_gen;
END_RCPP
}
// weibd0
double weibd0(Rcpp::List pars, arma::mat X1, arma::mat X2, arma::vec yvec, arma::uvec dupid, int dcate);
RcppExport SEXP _evgam_weibd0(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(weibd0(pars, X1, X2, yvec, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// weibd12
arma::mat weibd12(Rcpp::List pars, arma::mat X1, arma::mat X2, arma::vec yvec, arma::uvec dupid, int dcate);
RcppExport SEXP _evgam_weibd12(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(weibd12(pars, X1, X2, yvec, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}
// weibd34
arma::mat weibd34(Rcpp::List pars, arma::mat X1, arma::mat X2, arma::vec yvec, arma::uvec dupid, int dcate);
RcppExport SEXP _evgam_weibd34(SEXP parsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP yvecSEXP, SEXP dupidSEXP, SEXP dcateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yvec(yvecSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type dupid(dupidSEXP);
    Rcpp::traits::input_parameter< int >::type dcate(dcateSEXP);
    rcpp_result_gen = Rcpp::wrap(weibd34(pars, X1, X2, yvec, dupid, dcate));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_evgam_aldd0", (DL_FUNC) &_evgam_aldd0, 8},
    {"_evgam_aldd12", (DL_FUNC) &_evgam_aldd12, 8},
    {"_evgam_aldd34", (DL_FUNC) &_evgam_aldd34, 8},
    {"_evgam_egpd1d0", (DL_FUNC) &_evgam_egpd1d0, 7},
    {"_evgam_egpd1d12", (DL_FUNC) &_evgam_egpd1d12, 7},
    {"_evgam_egpd1d34", (DL_FUNC) &_evgam_egpd1d34, 7},
    {"_evgam_egpd2d0", (DL_FUNC) &_evgam_egpd2d0, 9},
    {"_evgam_egpd2d12", (DL_FUNC) &_evgam_egpd2d12, 9},
    {"_evgam_egpd2d34", (DL_FUNC) &_evgam_egpd2d34, 9},
    {"_evgam_egpd3d0", (DL_FUNC) &_evgam_egpd3d0, 7},
    {"_evgam_egpd3d12", (DL_FUNC) &_evgam_egpd3d12, 7},
    {"_evgam_egpd3d34", (DL_FUNC) &_evgam_egpd3d34, 7},
    {"_evgam_egpd4d0", (DL_FUNC) &_evgam_egpd4d0, 8},
    {"_evgam_egpd4d12", (DL_FUNC) &_evgam_egpd4d12, 8},
    {"_evgam_egpd4d34", (DL_FUNC) &_evgam_egpd4d34, 8},
    {"_evgam_exid0", (DL_FUNC) &_evgam_exid0, 8},
    {"_evgam_exid12", (DL_FUNC) &_evgam_exid12, 8},
    {"_evgam_exid34", (DL_FUNC) &_evgam_exid34, 8},
    {"_evgam_runmax", (DL_FUNC) &_evgam_runmax, 2},
    {"_evgam_expd0", (DL_FUNC) &_evgam_expd0, 5},
    {"_evgam_expd12", (DL_FUNC) &_evgam_expd12, 5},
    {"_evgam_expd34", (DL_FUNC) &_evgam_expd34, 5},
    {"_evgam_armapinv", (DL_FUNC) &_evgam_armapinv, 2},
    {"_evgam_armaginv", (DL_FUNC) &_evgam_armaginv, 2},
    {"_evgam_gaussd0", (DL_FUNC) &_evgam_gaussd0, 6},
    {"_evgam_gaussd12", (DL_FUNC) &_evgam_gaussd12, 6},
    {"_evgam_gaussd34", (DL_FUNC) &_evgam_gaussd34, 6},
    {"_evgam_gevd0", (DL_FUNC) &_evgam_gevd0, 7},
    {"_evgam_gevd12", (DL_FUNC) &_evgam_gevd12, 7},
    {"_evgam_gevd34", (DL_FUNC) &_evgam_gevd34, 7},
    {"_evgam_mean_arr", (DL_FUNC) &_evgam_mean_arr, 2},
    {"_evgam_ragged_mean_vec", (DL_FUNC) &_evgam_ragged_mean_vec, 2},
    {"_evgam_ragged_mean_mat", (DL_FUNC) &_evgam_ragged_mean_mat, 2},
    {"_evgam_ldgev", (DL_FUNC) &_evgam_ldgev, 4},
    {"_evgam_ldgev12", (DL_FUNC) &_evgam_ldgev12, 4},
    {"_evgam_ldgevagg", (DL_FUNC) &_evgam_ldgevagg, 5},
    {"_evgam_ldgevagg12", (DL_FUNC) &_evgam_ldgevagg12, 5},
    {"_evgam_gevcd0", (DL_FUNC) &_evgam_gevcd0, 7},
    {"_evgam_gevcd12", (DL_FUNC) &_evgam_gevcd12, 7},
    {"_evgam_gevcd34", (DL_FUNC) &_evgam_gevcd34, 7},
    {"_evgam_gpdd0", (DL_FUNC) &_evgam_gpdd0, 6},
    {"_evgam_gpdd12", (DL_FUNC) &_evgam_gpdd12, 6},
    {"_evgam_gpdd34", (DL_FUNC) &_evgam_gpdd34, 6},
    {"_evgam_gpdcd0", (DL_FUNC) &_evgam_gpdcd0, 6},
    {"_evgam_gpdcd12", (DL_FUNC) &_evgam_gpdcd12, 6},
    {"_evgam_gpdcd34", (DL_FUNC) &_evgam_gpdcd34, 6},
    {"_evgam_gH1", (DL_FUNC) &_evgam_gH1, 6},
    {"_evgam_gH2", (DL_FUNC) &_evgam_gH2, 7},
    {"_evgam_gH3", (DL_FUNC) &_evgam_gH3, 8},
    {"_evgam_gH4", (DL_FUNC) &_evgam_gH4, 9},
    {"_evgam_gH5", (DL_FUNC) &_evgam_gH5, 10},
    {"_evgam_pp1d0", (DL_FUNC) &_evgam_pp1d0, 6},
    {"_evgam_pp1d12", (DL_FUNC) &_evgam_pp1d12, 6},
    {"_evgam_pp1d34", (DL_FUNC) &_evgam_pp1d34, 6},
    {"_evgam_pp2d0", (DL_FUNC) &_evgam_pp2d0, 6},
    {"_evgam_pp2d12", (DL_FUNC) &_evgam_pp2d12, 5},
    {"_evgam_pp2d34", (DL_FUNC) &_evgam_pp2d34, 5},
    {"_evgam_ppcd0", (DL_FUNC) &_evgam_ppcd0, 6},
    {"_evgam_ppcd12", (DL_FUNC) &_evgam_ppcd12, 5},
    {"_evgam_ppcd34", (DL_FUNC) &_evgam_ppcd34, 5},
    {"_evgam_ppexi1d0", (DL_FUNC) &_evgam_ppexi1d0, 7},
    {"_evgam_ppexi1d12", (DL_FUNC) &_evgam_ppexi1d12, 7},
    {"_evgam_ppexi1d34", (DL_FUNC) &_evgam_ppexi1d34, 7},
    {"_evgam_ppexi2d0", (DL_FUNC) &_evgam_ppexi2d0, 7},
    {"_evgam_ppexi2d12", (DL_FUNC) &_evgam_ppexi2d12, 7},
    {"_evgam_ppexi2d34", (DL_FUNC) &_evgam_ppexi2d34, 7},
    {"_evgam_weibd0", (DL_FUNC) &_evgam_weibd0, 6},
    {"_evgam_weibd12", (DL_FUNC) &_evgam_weibd12, 6},
    {"_evgam_weibd34", (DL_FUNC) &_evgam_weibd34, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_evgam(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
