# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aldd0 <- function(pars, X1, X2, ymat, tau, C, dupid, dcate, nhere) {
    .Call(`_evgam_aldd0`, pars, X1, X2, ymat, tau, C, dupid, dcate, nhere)
}

aldd12 <- function(pars, X1, X2, ymat, tau, C, dupid, dcate, nhere) {
    .Call(`_evgam_aldd12`, pars, X1, X2, ymat, tau, C, dupid, dcate, nhere)
}

aldd34 <- function(pars, X1, X2, ymat, tau, C, dupid, dcate, nhere) {
    .Call(`_evgam_aldd34`, pars, X1, X2, ymat, tau, C, dupid, dcate, nhere)
}

bgevd0 <- function(pars, X1, X2, X3, ymat, dupid, dcate, other, nhere) {
    .Call(`_evgam_bgevd0`, pars, X1, X2, X3, ymat, dupid, dcate, other, nhere)
}

bgevd12 <- function(pars, X1, X2, X3, ymat, dupid, dcate, other, nhere) {
    .Call(`_evgam_bgevd12`, pars, X1, X2, X3, ymat, dupid, dcate, other, nhere)
}

bgevd34 <- function(pars, X1, X2, X3, ymat, dupid, dcate, other, nhere) {
    .Call(`_evgam_bgevd34`, pars, X1, X2, X3, ymat, dupid, dcate, other, nhere)
}

#' Conditional extreme value model negative log-likelihood
#'
#' @param pars a list of vectors of coefficients for each bGEV parameter
#' @param X1 a design matrix for (transformed) alpha
#' @param X2 a design matrix for (transformed) beta
#' @param X3 a design matrix for mu
#' @param X4 a design matrix for (transformed) sigma
#' @param ymat a matrix
#' @param xmat a matrix
#' @param dupid a scalar or vector, identifying duplicates in Xs; -1 corresponds to no duplicates
#' @return condexd0 a scalar, the negative log-likelihood
#' @return condexd12 a matrix, first then second derivatives w.r.t. parameters
#' @return condexd34 a matrix, third then fourth derivatives w.r.t. parameters
#' @examples
#' ## to follow
#' @export
condexd0 <- function(pars, X1, X2, X3, X4, ymat, xmat, dupid, dcate, nhere) {
    .Call(`_evgam_condexd0`, pars, X1, X2, X3, X4, ymat, xmat, dupid, dcate, nhere)
}

#' @rdname condexd0
condexd12 <- function(pars, X1, X2, X3, X4, ymat, xmat, dupid, dcate, nhere) {
    .Call(`_evgam_condexd12`, pars, X1, X2, X3, X4, ymat, xmat, dupid, dcate, nhere)
}

#' @rdname condexd0
condexd34 <- function(pars, X1, X2, X3, X4, ymat, xmat, dupid, dcate, nhere) {
    .Call(`_evgam_condexd34`, pars, X1, X2, X3, X4, ymat, xmat, dupid, dcate, nhere)
}

egpd1d0 <- function(pars, X1, X2, X3, yvec, dupid, dcate) {
    .Call(`_evgam_egpd1d0`, pars, X1, X2, X3, yvec, dupid, dcate)
}

egpd1d12 <- function(pars, X1, X2, X3, yvec, dupid, dcate) {
    .Call(`_evgam_egpd1d12`, pars, X1, X2, X3, yvec, dupid, dcate)
}

egpd1d34 <- function(pars, X1, X2, X3, yvec, dupid, dcate) {
    .Call(`_evgam_egpd1d34`, pars, X1, X2, X3, yvec, dupid, dcate)
}

egpd2d0 <- function(pars, X1, X2, X3, X4, X5, yvec, dupid, dcate) {
    .Call(`_evgam_egpd2d0`, pars, X1, X2, X3, X4, X5, yvec, dupid, dcate)
}

egpd2d12 <- function(pars, X1, X2, X3, X4, X5, yvec, dupid, dcate) {
    .Call(`_evgam_egpd2d12`, pars, X1, X2, X3, X4, X5, yvec, dupid, dcate)
}

egpd2d34 <- function(pars, X1, X2, X3, X4, X5, yvec, dupid, dcate) {
    .Call(`_evgam_egpd2d34`, pars, X1, X2, X3, X4, X5, yvec, dupid, dcate)
}

egpd3d0 <- function(pars, X1, X2, X3, yvec, dupid, dcate) {
    .Call(`_evgam_egpd3d0`, pars, X1, X2, X3, yvec, dupid, dcate)
}

egpd3d12 <- function(pars, X1, X2, X3, yvec, dupid, dcate) {
    .Call(`_evgam_egpd3d12`, pars, X1, X2, X3, yvec, dupid, dcate)
}

egpd3d34 <- function(pars, X1, X2, X3, yvec, dupid, dcate) {
    .Call(`_evgam_egpd3d34`, pars, X1, X2, X3, yvec, dupid, dcate)
}

egpd4d0 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate) {
    .Call(`_evgam_egpd4d0`, pars, X1, X2, X3, X4, yvec, dupid, dcate)
}

egpd4d12 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate) {
    .Call(`_evgam_egpd4d12`, pars, X1, X2, X3, X4, yvec, dupid, dcate)
}

egpd4d34 <- function(pars, X1, X2, X3, X4, yvec, dupid, dcate) {
    .Call(`_evgam_egpd4d34`, pars, X1, X2, X3, X4, yvec, dupid, dcate)
}

exid0 <- function(yvec, zvec, pars, nmax, X, dupid, dcate, link) {
    .Call(`_evgam_exid0`, yvec, zvec, pars, nmax, X, dupid, dcate, link)
}

exid12 <- function(yvec, zvec, pars, nmax, X, dupid, dcate, link) {
    .Call(`_evgam_exid12`, yvec, zvec, pars, nmax, X, dupid, dcate, link)
}

exid34 <- function(yvec, zvec, pars, nmax, X, dupid, dcate, link) {
    .Call(`_evgam_exid34`, yvec, zvec, pars, nmax, X, dupid, dcate, link)
}

#' Running maximum
#' 
#' Running \eqn{n}-value maximum and data frame with variable swapped for running maximum
#'
#' @param y a vector
#' @param n an integer giving the number of observations to calculate running maxmimum over; defaults to 2
#'
#' @return \code{runmax} returns a vector of the same dimension as \code{y}
#'
#' @examples
#' runmax(runif(10), 5)
#'
#' @name runmax
#'
#' @export
runmax <- function(y, n) {
    .Call(`_evgam_runmax`, y, n)
}

expd0 <- function(pars, X1, yvec, dupid, dcate) {
    .Call(`_evgam_expd0`, pars, X1, yvec, dupid, dcate)
}

expd12 <- function(pars, X1, yvec, dupid, dcate) {
    .Call(`_evgam_expd12`, pars, X1, yvec, dupid, dcate)
}

expd34 <- function(pars, X1, yvec, dupid, dcate) {
    .Call(`_evgam_expd34`, pars, X1, yvec, dupid, dcate)
}

armapinv <- function(x, tol) {
    .Call(`_evgam_armapinv`, x, tol)
}

armaginv <- function(x, tol) {
    .Call(`_evgam_armaginv`, x, tol)
}

gaussd0 <- function(pars, X1, X2, yvec, dupid, dcate) {
    .Call(`_evgam_gaussd0`, pars, X1, X2, yvec, dupid, dcate)
}

gaussd12 <- function(pars, X1, X2, yvec, dupid, dcate) {
    .Call(`_evgam_gaussd12`, pars, X1, X2, yvec, dupid, dcate)
}

gaussd34 <- function(pars, X1, X2, yvec, dupid, dcate) {
    .Call(`_evgam_gaussd34`, pars, X1, X2, yvec, dupid, dcate)
}

gev2d0 <- function(pars, X1, X2, X3, ymat, dupid, dcate, nhere) {
    .Call(`_evgam_gev2d0`, pars, X1, X2, X3, ymat, dupid, dcate, nhere)
}

gev2d12 <- function(pars, X1, X2, X3, ymat, dupid, dcate, nhere) {
    .Call(`_evgam_gev2d12`, pars, X1, X2, X3, ymat, dupid, dcate, nhere)
}

gev2d34 <- function(pars, X1, X2, X3, ymat, dupid, dcate, nhere) {
    .Call(`_evgam_gev2d34`, pars, X1, X2, X3, ymat, dupid, dcate, nhere)
}

gev2spd0 <- function(pars, X1, X2, X3, ymat, dupid, dcate, nhere) {
    .Call(`_evgam_gev2spd0`, pars, X1, X2, X3, ymat, dupid, dcate, nhere)
}

gev2spd12 <- function(pars, X1, X2, X3, ymat, dupid, dcate, nhere) {
    .Call(`_evgam_gev2spd12`, pars, X1, X2, X3, ymat, dupid, dcate, nhere)
}

gev2spd34 <- function(pars, X1, X2, X3, ymat, dupid, dcate, nhere) {
    .Call(`_evgam_gev2spd34`, pars, X1, X2, X3, ymat, dupid, dcate, nhere)
}

gevd0 <- function(pars, X1, X2, X3, yvec, dupid, dcate) {
    .Call(`_evgam_gevd0`, pars, X1, X2, X3, yvec, dupid, dcate)
}

gevd12 <- function(pars, X1, X2, X3, yvec, dupid, dcate) {
    .Call(`_evgam_gevd12`, pars, X1, X2, X3, yvec, dupid, dcate)
}

gevd34 <- function(pars, X1, X2, X3, yvec, dupid, dcate) {
    .Call(`_evgam_gevd34`, pars, X1, X2, X3, yvec, dupid, dcate)
}

mean_arr <- function(x, n) {
    .Call(`_evgam_mean_arr`, x, n)
}

ragged_mean_vec <- function(x, n) {
    .Call(`_evgam_ragged_mean_vec`, x, n)
}

ragged_mean_mat <- function(x, n) {
    .Call(`_evgam_ragged_mean_mat`, x, n)
}

ldgev <- function(yvec, muvec, lpsivec, xivec) {
    .Call(`_evgam_ldgev`, yvec, muvec, lpsivec, xivec)
}

ldgev12 <- function(yvec, muvec, lpsivec, xivec) {
    .Call(`_evgam_ldgev12`, yvec, muvec, lpsivec, xivec)
}

ldgevagg_logit <- function(yvec, muvec, lpsivec, xivec, thetavec) {
    .Call(`_evgam_ldgevagg_logit`, yvec, muvec, lpsivec, xivec, thetavec)
}

ldgevagg12_logit <- function(yvec, muvec, lpsivec, xivec, thetavec) {
    .Call(`_evgam_ldgevagg12_logit`, yvec, muvec, lpsivec, xivec, thetavec)
}

ldgevagg <- function(yvec, muvec, lpsivec, xivec, thetavec) {
    .Call(`_evgam_ldgevagg`, yvec, muvec, lpsivec, xivec, thetavec)
}

ldgevagg12 <- function(yvec, muvec, lpsivec, xivec, thetavec) {
    .Call(`_evgam_ldgevagg12`, yvec, muvec, lpsivec, xivec, thetavec)
}

gevcd0 <- function(pars, X1, X2, X3, ymat, dupid, dcate) {
    .Call(`_evgam_gevcd0`, pars, X1, X2, X3, ymat, dupid, dcate)
}

gevcd12 <- function(pars, X1, X2, X3, ymat, dupid, dcate) {
    .Call(`_evgam_gevcd12`, pars, X1, X2, X3, ymat, dupid, dcate)
}

gevcd34 <- function(pars, X1, X2, X3, ymat, dupid, dcate) {
    .Call(`_evgam_gevcd34`, pars, X1, X2, X3, ymat, dupid, dcate)
}

gpdd0 <- function(pars, X1, X2, yvec, dupid, dcate) {
    .Call(`_evgam_gpdd0`, pars, X1, X2, yvec, dupid, dcate)
}

gpdd12 <- function(pars, X1, X2, yvec, dupid, dcate) {
    .Call(`_evgam_gpdd12`, pars, X1, X2, yvec, dupid, dcate)
}

gpdd34 <- function(pars, X1, X2, yvec, dupid, dcate) {
    .Call(`_evgam_gpdd34`, pars, X1, X2, yvec, dupid, dcate)
}

gpdabd0 <- function(pars, X1, X2, yvec, ab, dupid, dcate) {
    .Call(`_evgam_gpdabd0`, pars, X1, X2, yvec, ab, dupid, dcate)
}

gpdabd12 <- function(pars, X1, X2, yvec, ab, dupid, dcate) {
    .Call(`_evgam_gpdabd12`, pars, X1, X2, yvec, ab, dupid, dcate)
}

gpdabd34 <- function(pars, X1, X2, yvec, ab, dupid, dcate) {
    .Call(`_evgam_gpdabd34`, pars, X1, X2, yvec, ab, dupid, dcate)
}

gpdcd0 <- function(pars, X1, X2, ymat, dupid, dcate) {
    .Call(`_evgam_gpdcd0`, pars, X1, X2, ymat, dupid, dcate)
}

gpdcd12 <- function(pars, X1, X2, ymat, dupid, dcate) {
    .Call(`_evgam_gpdcd12`, pars, X1, X2, ymat, dupid, dcate)
}

gpdcd34 <- function(pars, X1, X2, ymat, dupid, dcate) {
    .Call(`_evgam_gpdcd34`, pars, X1, X2, ymat, dupid, dcate)
}

.gH1 <- function(gh, X1, dupid, dcate, sand, deriv) {
    .Call(`_evgam_gH1`, gh, X1, dupid, dcate, sand, deriv)
}

.gH2 <- function(gh, X1, X2, dupid, dcate, sand, deriv) {
    .Call(`_evgam_gH2`, gh, X1, X2, dupid, dcate, sand, deriv)
}

.gH3 <- function(gh, X1, X2, X3, dupid, dcate, sand, deriv) {
    .Call(`_evgam_gH3`, gh, X1, X2, X3, dupid, dcate, sand, deriv)
}

.gH4 <- function(gh, X1, X2, X3, X4, dupid, dcate, sand, deriv) {
    .Call(`_evgam_gH4`, gh, X1, X2, X3, X4, dupid, dcate, sand, deriv)
}

.gH5 <- function(gh, X1, X2, X3, X4, X5, dupid, dcate, sand, deriv) {
    .Call(`_evgam_gH5`, gh, X1, X2, X3, X4, X5, dupid, dcate, sand, deriv)
}

.gH6 <- function(gh, X1, X2, X3, X4, X5, X6, dupid, dcate, sand, deriv) {
    .Call(`_evgam_gH6`, gh, X1, X2, X3, X4, X5, X6, dupid, dcate, sand, deriv)
}

.gH1sp <- function(gh, X1, dupid, dcate, sand, deriv) {
    .Call(`_evgam_gHsp1`, gh, X1, dupid, dcate, sand, deriv)
}

.gHsp2 <- function(gh, X1, X2, dupid, dcate, sand, deriv) {
    .Call(`_evgam_gHsp2`, gh, X1, X2, dupid, dcate, sand, deriv)
}

.gHsp3 <- function(gh, X1, X2, X3, dupid, dcate, sand, deriv) {
    .Call(`_evgam_gHsp3`, gh, X1, X2, X3, dupid, dcate, sand, deriv)
}

.gHsp4 <- function(gh, X1, X2, X3, X4, dupid, dcate, sand, deriv) {
    .Call(`_evgam_gHsp4`, gh, X1, X2, X3, X4, dupid, dcate, sand, deriv)
}

.gHsp5 <- function(gh, X1, X2, X3, X4, X5, dupid, dcate, sand, deriv) {
    .Call(`_evgam_gHsp5`, gh, X1, X2, X3, X4, X5, dupid, dcate, sand, deriv)
}

.gHsp6 <- function(gh, X1, X2, X3, X4, X5, X6, dupid, dcate, sand, deriv) {
    .Call(`_evgam_gHsp6`, gh, X1, X2, X3, X4, X5, X6, dupid, dcate, sand, deriv)
}

pp1d0 <- function(pars, X1, X2, X3, yvec, wvec) {
    .Call(`_evgam_pp1d0`, pars, X1, X2, X3, yvec, wvec)
}

pp1d12 <- function(pars, X1, X2, X3, yvec, wvec) {
    .Call(`_evgam_pp1d12`, pars, X1, X2, X3, yvec, wvec)
}

pp1d34 <- function(pars, X1, X2, X3, yvec, wvec) {
    .Call(`_evgam_pp1d34`, pars, X1, X2, X3, yvec, wvec)
}

pp2d0 <- function(pars, X1, X2, X3, yvec, wvec) {
    .Call(`_evgam_pp2d0`, pars, X1, X2, X3, yvec, wvec)
}

pp2d12 <- function(pars, X1, X2, X3, yvec) {
    .Call(`_evgam_pp2d12`, pars, X1, X2, X3, yvec)
}

pp2d34 <- function(pars, X1, X2, X3, yvec) {
    .Call(`_evgam_pp2d34`, pars, X1, X2, X3, yvec)
}

ppcd0 <- function(pars, X1, X2, X3, yvec, wvec) {
    .Call(`_evgam_ppcd0`, pars, X1, X2, X3, yvec, wvec)
}

ppcd12 <- function(pars, X1, X2, X3, yvec) {
    .Call(`_evgam_ppcd12`, pars, X1, X2, X3, yvec)
}

ppcd34 <- function(pars, X1, X2, X3, yvec) {
    .Call(`_evgam_ppcd34`, pars, X1, X2, X3, yvec)
}

ppexi1d0 <- function(pars, X1, X2, X3, X4, yvec, wvec) {
    .Call(`_evgam_ppexi1d0`, pars, X1, X2, X3, X4, yvec, wvec)
}

ppexi1d12 <- function(pars, X1, X2, X3, X4, yvec, wvec) {
    .Call(`_evgam_ppexi1d12`, pars, X1, X2, X3, X4, yvec, wvec)
}

ppexi1d34 <- function(pars, X1, X2, X3, X4, yvec, wvec) {
    .Call(`_evgam_ppexi1d34`, pars, X1, X2, X3, X4, yvec, wvec)
}

ppexi2d0 <- function(pars, X1, X2, X3, X4, yvec, wvec) {
    .Call(`_evgam_ppexi2d0`, pars, X1, X2, X3, X4, yvec, wvec)
}

ppexi2d12 <- function(pars, X1, X2, X3, X4, yvec, wvec) {
    .Call(`_evgam_ppexi2d12`, pars, X1, X2, X3, X4, yvec, wvec)
}

ppexi2d34 <- function(pars, X1, X2, X3, X4, yvec, wvec) {
    .Call(`_evgam_ppexi2d34`, pars, X1, X2, X3, X4, yvec, wvec)
}

rcpparma_hello_world <- function() {
    .Call(`_evgam_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_evgam_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_evgam_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_evgam_rcpparma_bothproducts`, x)
}

weibd0 <- function(pars, X1, X2, yvec, dupid, dcate) {
    .Call(`_evgam_weibd0`, pars, X1, X2, yvec, dupid, dcate)
}

weibd12 <- function(pars, X1, X2, yvec, dupid, dcate) {
    .Call(`_evgam_weibd12`, pars, X1, X2, yvec, dupid, dcate)
}

weibd34 <- function(pars, X1, X2, yvec, dupid, dcate) {
    .Call(`_evgam_weibd34`, pars, X1, X2, yvec, dupid, dcate)
}

